language: python
python:
  - "2.7.12"
# command to install dependencies
install:
  - pip install nose Faker codecov
  - python setup.py install
# command to run tests
script:
  - "nosetests --with-coverage --cover-package=telium test/*.py"
after_success:
  - codecov